id: IF7D3B55F
legacy_id: P006808
ocr_import_info:
  bdrc_scan_id: W27875
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T01:19:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T07:34:33.375639+00:00'
last_modified: 2022-09-02 15:34:48.194012
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27875
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27875
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་བསྟན་པའི་ཤིང་རྟ་དཔལ་ཡུལ་པའི་ཕྱག་བཞེས་ཀྱི་གདངས་དབྱངས།
  author: པད་ནོར ༠༢་ཐུབ་བསྟན་ཆོས་ཀྱི་གླང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6354321914117078
  ocr_word_median_confidence_index: 0.7200000286102295
quality: null
bases:
  I4494:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4494
      total_pages: 240
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4494.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6354321914117078
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
