id: IF7D3B55F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T01:20:37+00:00'
last_modified: '2022-06-08T07:00:03.430476+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27875
  title: སྔ་འགྱུར་བསྟན་པའི་ཤིང་རྟ་དཔལ་ཡུལ་པའི་ཕྱག་བཞེས་ཀྱི་གདངས་དབྱངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A631:
      image_group_id: I4494
      title: ''
      total_pages: 240
      order: 1
      base_file: A631.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
